project_id = "laluxmwarlejdwyboudz"

[functions.blockchain-monitor]
verify_jwt = false

[functions.sync-system-parameters]
verify_jwt = false

[functions.sync-wallet-kind-30889]
verify_jwt = false

[functions.fetch-wallet-balance]
verify_jwt = false

[functions.sync-profile-data]
verify_jwt = false

[functions.kind-87005-new-lana-registration]
verify_jwt = false

[functions.kind-cron-87003-monitoring-unregistered-coins]
verify_jwt = false

[functions.kind-cron-37772-lanaknight-registry]
verify_jwt = false

[functions.return-lanas-and-send-KIND-87009]
verify_jwt = false

[functions.consolidate-wallet]
verify_jwt = false

[functions.analyze-wallet-utxos]
verify_jwt = false

[functions.register-virgin-wallets]
verify_jwt = false

[functions.delete-wallet]
verify_jwt = false

[functions.update-wallet-notes]
verify_jwt = false

[functions.freeze-wallets]
verify_jwt = false

[functions.check]
verify_jwt = false

[functions.admin-delete-wallet]
verify_jwt = false
